version: "3.4"

services:
  dev:
    container_name: ml-reversi-dev
    working_dir: /app
    image: python:3.7
    tty: true
    profiles:
      - extra
    volumes:
      - type: bind
        source: .
        target: /app
  prod:
    container_name: ml-reversi-prod
    build:
      context: .
    ports:
      - 8000:8000


